channels:
- device: Chat (TC-Helicon GoXLR)
- device: Music (TC-Helicon GoXLR)
- device: Game (TC-Helicon GoXLR)
- device: System (TC-Helicon GoXLR)
- - device: Speakers (Logitech G733 Gaming Headset)
  - device: Speakers (Realtek High Definition Audio)
- key:
    action:
      mute:
        channel: 4
# 0: master
# 1: chrome.exe
# 2: spotify.exe
# 3:
#   - pathofexile_x64.exe
#   - rocketleague.exe
# 4: discord.exe

invert_sliders: false

com_port: COM8
baud_rate: 9600

noise_reduction:
  default_epsilon: 20
  default_weight: 0.2
  # channels:
  # #   0:
  # #     epsilon: 18
  # #     weight: 0.2
  # #   1:
  # #     epsilon: 18
  # #     weight: 0.2
  #   5:
  #     epsilon: 100
  #     weight: 1
