---
com_port: COM9
baud_rate: 9600

noise_reduction:
  default_epsilon: 20
  default_weight: 0.2
  default_debounce_period: 300

analog_channels:
- targets:
  - device: Speakers (2- Logitech G733 Gaming Headset)
  - device: Speakers (Realtek High Definition Audio)
  noise_reduction:
    epsilon: 10
    weight: 0.1
- invert: true
  targets:
  - device: System (TC-Helicon GoXLR)
- targets:
  - device: Game (TC-Helicon GoXLR)
- targets:
  - device: Music (TC-Helicon GoXLR)
- targets:
  - device: Chat (TC-Helicon GoXLR)
- targets:
  - device: Sample (TC-Helicon GoXLR)
- targets:
  - process: firefox.exe
- targets:
  - process: msedge.exe

digital_channels:
  - mute:
      targets:
      - device: System (TC-Helicon GoXLR)
    noise_reduction:
      debounce_period: 100
...
