---
$schema: http://json-schema.org/draft/2019-09/schema#
$id: https://github.com/reversefold/deej/config.schema.yaml
title: JSON Schema for deej config.yaml
type: object
properties:
  analog_channels:
    type: array
    items:
      type: object
      properties:
        invert:
          type: boolean
        targets:
          type: array
          items:
            $ref: "#/definitions/target"
        noise_reduction:
          type: object
          properties:
            epsilon: {type: integer}
            weight: {type: number}
          additionalProperties: false
      required: [targets]
      additionalProperties: false
  digital_channels:
    type: array
    items:
      type: object
      properties:
        invert: {type: boolean}
        mute:
          type: object
          properties:
            targets:
              type: array
              items:
                $ref: "#/definitions/target"
          required: [targets]
          additionalProperties: false
        noise_reduction:
          type: object
          properties:
            debounce_period: {type: integer}
          additionalProperties: false
      required: [mute]
      additionalProperties: false
  invert_sliders: {type: boolean}
  com_port: {type: string}
  baud_rate: {type: integer}
  noise_reduction:
    type: object
    properties:
      default_epsilon: {type: integer}
      default_weight: {type: number}
      default_debounce_period: {type: integer}
    additionalProperties: false
additionalProperties: false

definitions:
  targets:
    type: array
    minItems: 1
    items:
      $ref: "#/definitions/target"
  target:
    # oneOf:
    # - type: string
    # -
      type: object
      properties:
        device: {type: string}
        process: {type: string}
        epsilon: {type: integer}
        weight: {type: number}
      oneOf:
      - required: [device]
      - required: [process]
      additionalProperties: false
...
